const CHANGE_CURRENT_SCREEN = 'CHANGE_CURRENT_SCREEN';
const CHANGE_ERROR_MESSAGE = 'CHANGE_ERROR_MESSAGE';
const GET_NEWS = 'GET_NEWS';

export default {
  CHANGE_CURRENT_SCREEN,
  CHANGE_ERROR_MESSAGE,
  GET_NEWS,
};